### ISSUE TITLE
how do I set the dapr appid thru code/options? could you all add some examples for options?

### ISSUE THREAD

**Issue by aktxyz** [man-group/dapr-sidekick-dotnet#24]

**Comment by badgeratu** [comment]
There's a couple of ways to do this, the simplest is to set it specifically in `appsettings.json`:
```
{
  "DaprSidekick": {
    "Sidecar": {
      "AppId": "MyApplication"
    }
  }
}
```
Anything in the [DaprSidecarOptions](../blob/main/src/Man.Dapr.Sidekick/Options/DaprSidecarOptions.cs) can be put in the `Sidecar` section above.

Or you can do it in code via the `AppDaprSidekick()` extension method:
```
// Add Dapr Sidekick
services.AddDaprSidekick(Configuration, configure =>
{
    configure.Sidecar ??= new Man.Dapr.Sidekick.DaprSidecarOptions();
    configure.Sidecar.AppId = "MyApplication";
});
```

Or you can use the regular `IPostConfigureOptions<T>` pattern to register a post-configure handler into which you can inject anything to help you override the options at runtime.

**Comment by aktxyz** [comment]
thanks ! could of sworn I had tried the appsettings.json version, must have had something whacked
