### ISSUE TITLE
Namespace environment variable not set

### ISSUE THREAD

**Issue by helmerm** [man-group/dapr-sidekick-dotnet#28]
## Expected Behavior

Namespace environment variable set on daprd process.

## Actual Behavior

Namespace variable not set (verified with ProcessExplorer).
DAPR_* variables are set.

## Steps to Reproduce the Problem

CLI version: 1.4.0
Runtime version: 1.3.0
Man.Dapr.Sidekick 1.1.0
Windows 10

* Create component config which points to non-existing IP (see below)
* Set Namespace in json config to
  * only components from configured namespace should be loaded
* daprd will try to load component configuration and show connection error despite namespace in sidecar config
  * process component mqtt-pubsub error: init timeout for component mqtt-pubsub exceeded after 5s"

pubsub.yml

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-pubsub
  namespace: remote
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "mqtt://192.168.137.1:1883"

appsettings.json
  "DaprSidekick": {
    "Sidecar": {
      "Namespace": "local" 
    }
  }

## Release Note

RELEASE NOTE: **FIX** Missing Namespace environment variable.

**Comment by badgeratu** [comment]
Now available in [Release v1.2](../releases/tag/v1.2.0)
