### ISSUE TITLE
Dose dapr-sidekick Support dotnet apps deployed in IIS

### ISSUE THREAD

**Issue by dengyakui** [man-group/dapr-sidekick-dotnet#34]
## Ask your question here
We have several aspnet core 6 web apps deployed in windows server 2016 IIS, and the network is on-promised. can not use Docker. 
We always want to use Dapr to make some microservice, The biggest problem is the process daemon . If the server shutdown or restart, out app should be auto restarted,  so we choose IIS In Process Mode to publish our sites, because there are a bunches of toolchains like MSDeloy, VisualStudio, Rider, AzureDevops to support.
 But IIS can not start daprd process for app side car, if we use the default self-hosted mode, can not auto restart app or dapr side car , or directed start app as backgroud service, not to stuck with the console.
 
This project seems to solve out problem, but I found it can not properly start daprd when I pub the website to iis.
![image](https://user-images.githubusercontent.com/3945919/145178559-47c0d66a-e342-4fa3-9280-b627af5a287e.png)

**Comment by dengyakui** [comment]
I solved the problem~. By check the logs, it was the daprd.exe path problem,
the website app pool 's identity default to Network Service, so the problem is the user home dirs not exist daprd.exe
![image](https://user-images.githubusercontent.com/3945919/145188985-0309dee1-cdf6-40ae-a937-aee84cc9de28.png)

by change the iis application pool's identity to current user, Dapr start succeefully.

![image](https://user-images.githubusercontent.com/3945919/145189230-fbfd9876-c9b9-4112-99a0-e4d0e4687c38.png)


![image](https://user-images.githubusercontent.com/3945919/145189474-cc588e1b-8889-4395-85fb-a1fd127a952f.png)

**Comment by badgeratu** [comment]
Glad you were able to work it out! If you would prefer to run the AppPool under the regular identity then you can explicitly tell Sidekick where to find `daprd`. We do this ourselves as we push the dapr binaries to a non-user local directory such as `C:\dapr\latest` and use the following entry in `appsettings.json` to ensure they are picked up by Sidekick:
```
{
  "DaprSidekick": {
    "InitialDirectory": "C:\\dapr\\latest"
  }
}
```

**Comment by dengyakui** [comment]
Thanks

**Comment by ratku** [comment]
i have a aspnet core 6 web apps deployed in windows server IIS ,i need help,can you   wirte  a   step by step  ?
