### ISSUE TITLE
Sidekick in Console apps

### ISSUE THREAD

**Issue by stacyh3** [man-group/dapr-sidekick-dotnet#35]
This might be easier than I think, but is it possible to use Sidekick in a console app? I have a simulated message sender that I'm using for testing and Sidekick would make this much easier. I did look through the docs, but didn't find anything. I'll try to read through the code as well, but I wanted to save some time by asking here.

If this is not a currently supported scenario, it might be one that's worth looking at for the future.

**Comment by badgeratu** [comment]
Yes, Sidekick is designed for Console use as well, where you need to use the `DaprSidekickBuilder` class. See the [Wcf Sample](../tree/main/samples/NetFramework/WcfSample) for an example of how to get it working.

**Comment by stacyh3** [comment]
Thanks!
