### ISSUE TITLE
Slight delay after starting sidecar

### ISSUE THREAD

**Issue by riezebosch** [man-group/dapr-sidekick-dotnet#40]
I noticed when using sidekick to start the sidecar from an integration test the sidecar was not immediately able to handle requests. This was resolved by introducing a slight delay of ~200ms.

When trying to implement a solution for this I noticed that there's a synchronous API while there's a lot of asynchrony involved.

I have a PR ready to show how I'm trying to use your library and where it doesn't fit that purpose right now.

**Comment by badgeratu** [comment]
First, many thanks for your interest in Sidekick :) As the `daprd` process can conceivably go down/restart at any time, we don't provide a "wait on startup" as such but instead provide a way to check the process status so you can wait for its availability in your code. This is done by checking `DaprProcessInfo` returned by `IDaprSidecarHost`. So in your integration test you could do something like this:

```
// Wait for the host to become available
while (!sidekick.Sidecar.GetProcessInfo().IsRunning)
{
  // Dapr not yet started. Wait for 100ms.
  System.Threading.Thread.Sleep(100);
}

I appreciate this does put the responsibility on the calling application to check the status, but that's really the case anyway when you are using Dapr (which is an external process) whether you are using Sidekick or not. We just make sure Sidekick gives you a simple way to determine the status of `daprd` at any time and code around it appropriately.

**Comment by riezebosch** [comment]
I didn't know about sidekick before I read this blog: https://markheath.net/post/running-locally-with-dapr-options. but I implemented my own solution to manage the self-hosted sidecar from an integration test: https://github.com/riezebosch/dapr.wrapr

There I scan the actual output of the sidecar to make sure it is up and running. Another benefit it has is that I made it disposable to make the cleanup easier.

I understand that it is a slightly different use case than you have/had but I was happy to see it was quite frictionless to drop in your (battle-tested) solution.

**Comment by riezebosch** [comment]
Not too sure. If you think about supporting the use of this library in a testing context it would make sense to fix it in one place. Maybe a separate method (or even an extension method) to await the sidecar until it is ready. In the meantime, I'll stick to my own package since it is geared a bit more towards short-lived sidecars and cleanup on disposal.

Feel free to close this issue or takeover the PR and do whatever you like.
