### ISSUE TITLE
Will Dapr Sidekick be further developed and maintained?

### ISSUE THREAD

**Issue by ChristianWeyer** [man-group/dapr-sidekick-dotnet#44]
Hey all,

this project looks really cool and helpful :-)

Are there any concrete plans to further maintain it?
Like moving it to .NET 6.0 and also supporting future versions of Dapr?

Thanks.

**Comment by badgeratu** [comment]
Hi, thanks for your interest in Sidekick. The project is maintained and we'll add new features as needed, however we've not come across any we need ourselves for some time. It works fine with .NET 6 and the latest version of Dapr (1.7.3) and we are using it ourselves with those.

The point about Sidekick is it's a very slim component for launching & monitoring the sidecar - it doesn't need a reference to the Dapr SDK and isn't tied to any particular version of Dapr.

If there's a feature you'd like to request or submit, raise an issue for it!

**Comment by badgeratu** [comment]
Closing as answered
