### ISSUE TITLE
client.CheckHealthAsync() return false

### ISSUE THREAD

**Issue by BartNetJS** [man-group/dapr-sidekick-dotnet#50]
When execute client.CheckHealthAsync() it return false when running with dapr sidekick
When i run it with dapr run ... it returns true.

Also the same with WaitForSidecarAsync, it works with dapr run, but not with the dapr sidekick.

Any idea why? Is it because daprd is not discovered? The same issue with dashboard that is able to discover dapr services started with daprd?

**Comment by BartNetJS** [comment]
I figured it out when working on the sample for this question https://github.com/man-group/dapr-sidekick-dotnet/issues/51
Thanks!

**Comment by badgeratu** [comment]
Closing as completed
